# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

test_that("f_display_indicator_analysis works", {
  expect_true(inherits(f_display_indicator_analysis, "function")) 
})
