---
title: "Building the MVI"
output: html_notebook
---

Some very brief notes to build the MVI and play around with it at an early stage.

The construction of the MVI is now all in the file `build_MVI.R`. Specifically, if you source this file using `source()` (insert the file path of that file in the function), then run `MVI <- build_MVI()` it will build the MVI as it stands. You can of course edit the code in the function to change how the index is built.

If you change the input data you will have to make sure that `read_excel()` is pointing at the correct file. Also, the input data is expected to be in a format fairly similar to how it is in the current input spreadsheet.

When you have built the index, if you want to export to Excel run `export_to_excel(MVI)`. This will write an Excel spreadsheet to your working directory. The tabs you will be interested in will be at the end: "Results.FullScore" (table of scores) and "Results.FullRank" (table of ranks).

If you want to plot the index, do: 

```{r, eval=FALSE}
source(here::here("R/old","map_tests.R"))

plot_choropleth(MVI, dset = "Aggregated", iCode = "MVI")
```

You can plot other indicators on the map instead by changing `iCode`.

Let me know if you have any problems. I will begin formalising the code and tidying things up.
