# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Benefit of doubt aggregation
#' 
#' As used in compind package
#' 
#' @param x A numeric vector
#' 
#' @export
#' @examples
#' #
a_bod <- function(x){
  suppressMessages(Compind::ci_bod(x)$ci_bod_est)
}
