# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Wroclaw Taxonomic aggregation
#' 
#' As used in Compind package
#' 
#' @noRd
#' @examples
#' #
a_wroclaw <- function(x){
  suppressMessages(Compind::ci_wroclaw(x)$ci_wroclaw_est)
}
