# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Wroclaw Taxonomic aggregation
#' 
#' As used in Compind package
#' 
#' @noRd
#' @examples
#' #
a_wroclaw <- function(x){
  if(ncol(x) == 1){
    return(x[[1]])
  }
  suppressMessages(Compind::ci_wroclaw(x)$ci_wroclaw_est) |>
    as.numeric()
}
