# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Add indicators
#' 
#'  As `f_remove_indicators()` but adds indicators back in. Obviously only
#'  indicators that were originally present in the input data can be added.
#' 
#' @param coin The coin
#'              
#' @param add_indicators Character vector of indicator codes to add back in.
#'         
#' @importFrom COINr change_ind
#' 
#' @return coin Updated coin.
#' 
#' @export
#' @examples
#' MVI <- f_data_input(file_path = system.file("data_input/data_module-input.xlsx",
#'                                             package = "BuildIndex") )
#' 
#' # remove first
#' MVI <- f_remove_indicators(MVI, c("S.G.3", "A.M.1"))
#' # print method
#' MVI
#' 
#' # add one back
#' MVI <- f_add_indicators(MVI, "S.G.3")
#' MVI
f_add_indicators <- function(coin, add_indicators = NULL){

  # extract analysis
  ind_analysis <- coin$Analysis$Raw
  analysis_exists <- !is.null(ind_analysis)

  coin <- COINr::change_ind(coin, add = add_indicators, regen = TRUE)

  if(analysis_exists){
    # edit and replace analysis
    ind_analysis$FlaggedStats$Status[
      ind_analysis$FlaggedStats$iCode %in% add_indicators] <- "In"
    ind_analysis$Flags$Status[
      ind_analysis$Flags$iCode %in% add_indicators] <- FALSE

    coin$Analysis$Raw <- ind_analysis
  }

  if(!is.null(coin$Data$Aggregated)){
    coin <- f_generate_results(coin)
  }

  return(coin)

    
}
