# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Analyse indicators 
#' 
#' Takes a coin and outputs an analysis of indicators. The objective is to look
#' for any "statistically-problematic" indicators, based on:
#' 
#' - data availability
#' - high proportion of repeated data values
#' - outliers as defined by skew and kurtosis
#' - collinearity within first aggregation level (category)
#' - negative correlation within first aggregation level (category)
#' 
#' The output can be viewed in R or as an interactive data frame.
#' Uses Spearman rank correlation to deal with skewed distributions.
#' Operates on the Raw data set.
#' 
#' The output is a coin with the results attached. This is so that on export, the
#' results will also be exported easily.
#' 
#' @param coin The coin
#' 
#' @return coin Updated coin with analysis tables
#' 
#' @importFrom COINr get_stats get_corr_flags is.coin
#' 
#' @export
#' @examples
#' MVI <- f_data_input(file_path = system.file("data_input/data_module-input.xlsx",
#'                                             package = "BuildIndex") )
#' 
#' 
#' MVI <- f_analyse_indicators(MVI)
f_analyse_indicators <- function(coin){

  stopifnot(COINr::is.coin(coin))

  # Settings ----

  dat_avail_thresh <- 0.66
  skew_thresh <- 2
  kurt_thresh <- 3.5
  same_thresh <- 0.5
  collin_thresh <- 0.9
  neg_corr_thresh <- -0.4

  # Univariate stats ----

  df_stats <- COINr::get_stats(
    coin, dset = "Raw",
    t_skew = skew_thresh,
    t_kurt = kurt_thresh,
    t_avail = dat_avail_thresh,
    out2 = "df")

  # prep df for display
  df_disp <- df_stats[c("iCode", "Frc.Avail", "Frc.Same")]
  # add skew and kurt
  df_disp$SkewKurt <- paste0(signif(df_stats$Skew, 3)," / ", signif(df_stats$Kurt, 3))

  # we find which iCodes are flagged for which things
  # prep a df
  df_flag <- data.frame(iCode = df_disp$iCode)

  # in the flag df TRUE means it is flagged as having a problem
  df_flag$Frc.Avail <- df_stats$Flag.Avail == "LOW"
  df_flag$Frc.Same <- df_stats$Frc.Same > 0.5
  df_flag$SkewKurt <- df_stats$Flag.SkewKurt == "OUT"

  # Bivariate (correlations) ----

  df_collinear <- COINr::get_corr_flags(
    coin, dset = "Raw",
    cor_thresh = collin_thresh,
    thresh_type = "high",
    grouplev = 2,
    cortype = "spearman",
    use_directions = TRUE)

  df_flag$Collinear <- df_flag$iCode %in% c(df_collinear$Ind1, df_collinear$Ind2)

  df_negcorr <- COINr::get_corr_flags(
    coin, dset = "Raw",
    cor_thresh = neg_corr_thresh,
    thresh_type = "low",
    grouplev = 2,
    cortype = "spearman",
    use_directions = TRUE)

  df_flag$NegCorr <- df_flag$iCode %in% c(df_negcorr$Ind1, df_negcorr$Ind2)

  # Tidy and output ----

  # assemble a big table for viewing (to probably adjust yet)
  df_disp <- df_disp[match(df_flag$iCode, df_disp$iCode), ]

  # add correlation entries

  pairs_colin <- f_gather_correlations(df_collinear)
  df_disp$Collinear <- pairs_colin[match(df_disp$iCode, names(pairs_colin))]

  pairs_neg <- f_gather_correlations(df_negcorr)
  df_disp$NegCorr <- pairs_neg[match(df_disp$iCode, names(pairs_neg))]

  # status column (will be changed if indicators are added/removed)
  df_disp$Status <- "In"
  df_flag$Status <- FALSE

  # add outputs to coin
  coin$Analysis$Raw <- list(
    FlaggedStats = df_disp,
    Flags = df_flag
  )

  return(coin)
}
