# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Build index
#' 
#' this function builds the MVI. Assumes that at this point you have imported
#' your data and built the MVI coin. Also optionally you have analysed and
#' possibly removed indicators, but taken no further steps.
#' 
#' @param coin COIN object, or list with first entry is the indicator metadata, 
#'              second entry is the aggregation metadata
#'              
#' @importFrom COINr is.coin qTreat Normalise Aggregate
#' 
#' @return coin COIN object
#' 
#' @export
#' @examples
#' MVI <- f_data_input(file_path = system.file("data_input/data_module-input.xlsx",
#'                                             package = "BuildIndex") )
#' 
#' ## when using create a data-raw folder and put you data input xlsx file there
#' # MVI <- f_data_input(here::here("data-raw", "data_module-input.xlsx"))
#' 
#' f_build_index(coin = MVI)
f_build_index <- function(coin){

  stopifnot(COINr::is.coin(coin))

  # Settings ----

  max_winsorisation <- 5
  skew_thresh <- 2
  kurt_thresh <- 3.5

  # treat outliers
  coin <- COINr::qTreat(
    coin, dset = "Raw",
    winmax = max_winsorisation,
    skew_thresh = skew_thresh,
    kurt_thresh = kurt_thresh,
    f2 = "log_CT_plus")

  # normalise to [0, 100]
  coin <- COINr::Normalise(coin, dset = "Treated")

  # aggregate using weighted arithmetic mean
  coin <- COINr::Aggregate(coin, dset = "Normalised")

  # generate results tables
  coin <- f_generate_results(coin)

  return(coin)
    
}
