# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Data input
#' 
#' Outputs a constructed coin
#' Reads an Excel file found at `file_path` which is expected to be in a specific
#' format. See "inst/data_input/data_module-input.xlsx" for example.
#' .
#' 
#' @param file_path path to the excel file where we have the raw data - organised
#'      with the format exepected by COINR package
#'      
#' @importFrom readxl read_excel  cell_limits 
#' @importFrom COINr new_coin   
#' 
#' @return coin object with a COINR class
#' 
#' @export
#' @examples
#' MVI <- f_data_input(file_path = system.file("data_input/data_module-input.xlsx",
#'                                             package = "BuildIndex") )
#' 
#' ## when using create a data-raw folder and put you data input xlsx file there
#' # MVI <- f_data_input(here::here("data-raw", "data_module-input.xlsx"))
#' 
f_data_input <- function(file_path){
  
   # Settings ----

  # anchor points in spreadsheet
  idata_topleft <- c(5, 1)
  imeta_topleft <- c(1, 3)
  imeta_botleft <- c(5, 3)

  # col names to look for
  ucode_name <- "admin2Pcode"
  uname_name <- "Name"


  # Read in data ----

  iData <- readxl::read_excel(
    path = file_path, sheet = "Data",
    range = readxl::cell_limits(ul = idata_topleft, lr = c(NA, NA))
    )
  iMeta <- readxl::read_excel(
    path = file_path, sheet = "Data",
    range = readxl::cell_limits(ul = imeta_topleft,
                        lr = c(imeta_botleft[1], NA)),
    col_names = FALSE
  ) |> suppressMessages()
  
  
  ## @will Maybe need to do some format checking

  # Tidy iData ----

  names(iData)[names(iData) == ucode_name] <- "uCode"
  names(iData)[names(iData) == uname_name] <- "uName"


  # Tidy and merge metadata ----

  # tidy existing
  iMeta <- as.data.frame(t(iMeta))
  names(iMeta) <- c("Weight", "Direction", "Parent", "iName", "iCode")
  iMeta$Weight <- as.numeric(iMeta$Weight)
  iMeta$Direction <- as.numeric(iMeta$Direction)
  row.names(iMeta) <- NULL

  # add cols (ready for merge)
  iMeta$Level <- 1
  iMeta$Type <- "Indicator"

  # merge with aggregate levels
  
  ## @will - why not simply pulling this from the same excel ??
  
#  iMeta_aggs <- readRDS(here::here("inst/data_input", "iMeta_aggs.RDS"))
 iMeta_aggs <- readRDS(system.file("data_input/iMeta_aggs.RDS", package = "BuildIndex") ) 
  
  iMeta <- rbind(iMeta, iMeta_aggs)


  # Further tidying ----

  # remove indicators with no data

  i_nodata <- names(iData)[colSums(!is.na(iData)) == 0]
  iData <- iData[!(names(iData) %in% i_nodata)]
  iMeta <- iMeta[!(iMeta$iCode %in% i_nodata), ]

  if(length(i_nodata) > 0){
    message("Removed indicators with no data points: ",
            paste0(i_nodata, collapse = ", "))
  }

  # remove any second-level groups with no children

  no_children_1 <- iMeta$iCode[iMeta$Level == 2 & !(iMeta$iCode %in% iMeta$Parent)]
  iMeta <- iMeta[!(iMeta$iCode %in% no_children_1), ]

  if(length(no_children_1) > 0){
    message("Removed categories containing no indicators: ",
            paste0(no_children_1, collapse = ", "))
  }

  # remove any third-level groups with no children

  no_children_2 <- iMeta$iCode[iMeta$Level == 3 & !(iMeta$iCode %in% iMeta$Parent)]
  iMeta <- iMeta[!(iMeta$iCode %in% no_children_1), ]

  if(length(no_children_2) > 0){
    message("Removed dimensions containing no categories: ", no_children_2,
            paste0(no_children_2, collapse = ", "))
  }


  # Build coin and output ----

  coin <- COINr::new_coin(iData, iMeta, quietly = TRUE,
           level_names = c("Indicator", "Category", "Dimension", "Index"))
  
  return(coin)
    
}
