# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Display indicator analysis
#' 
#' Description
#' 
#' @param coin COIN object, or list with first entry is the indicator metadata, 
#'              second entry is the aggregation metadata
#'              
#' @param  filter_to_flagged   TRUE or FALSE
#' @importFrom COINr is.coin
#' @importFrom rlang abort
#' 
#' @return
#' 
#' @export
#' @examples
#' MVI <- f_data_input(file_path = system.file("data_input/data_module-input.xlsx",
#'                                             package = "BuildIndex") )
#' 
#' ## when using create a data-raw folder and put you data input xlsx file there
#' # MVI <- f_data_input(here::here("data-raw", "data_module-input.xlsx"))
#' 
#' MVI2 <- f_analyse_indicators(MVI)
#' 
#' f_display_indicator_analysis(MVI2)
f_display_indicator_analysis <- function(coin, filter_to_flagged = TRUE){

  stopifnot(COINr::is.coin(coin))

  Xd <- coin$Analysis$Raw$FlaggedStats
  Xh <- coin$Analysis$Raw$Flags

  if(is.null(Xd) || is.null(Xh)){
    rlang::abort("Indicator analysis not found in coin. Run f_analyse_indicators() first.")
  }

  if(filter_to_flagged){

    # only include rows with at least one flag
    include_rows <- rowSums( Xh[!(names(Xh) %in% c("iCode", "Status"))] ) > 0

    Xd <- Xd[include_rows, ]
    Xh <- Xh[include_rows, ]

  }

  f_highlight_DT(Xd, Xh)
    
}
