# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Title
#' 
#' 
#' 
# usethis::use_rmarkdown_template(
#   template_name = "Index_report",
#   template_dir = NULL,
#   template_description = "Index Review Report - html",
#   template_create_dir = TRUE
# )
#' 
#' @return
#' 
#' @export
#' @examples
#' f_export_report()
f_export_report <- function(){
  
    
}
