# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Export to excel
#' 
#' Simplified export to Excel with some formatting
#' Note if we change the index structure, the conditional formatting will need
#' to be adjusted.
#' 
#' 
#' @param coin The coin, with results present.
#' @param fname file name to write the results to.
#' 
#' @importFrom RColorBrewer brewer.pal
#' @importFrom openxlsx createWorkbook addWorksheet writeData writeDataTable
#'               conditionalFormatting saveWorkbook
#'               
#' @return Writes an Excel spreadsheet.
#' 
#' @export
#' @examples
#' MVI <- f_data_input(file_path = system.file("data_input/data_module-input.xlsx",
#'                                             package = "BuildIndex") )
#' 
#' ## when using create a data-raw folder and put you data input xlsx file there
#' # MVI <- f_data_input(here::here("data-raw", "data_module-input.xlsx"))
#' MVI <- f_analyse_indicators(MVI)
#' MVI <- f_build_index(MVI)
#' 
#' f_export_to_excel(coin = MVI, 
#'                   fname = here::here("inst", "index_export.xlsx"))
f_export_to_excel <- function(coin, fname = "index_export.xlsx"){

  l <- list()

  # Results
  l$Scores <- coin$Results$FullScore
  l$Ranks <- coin$Results$FullRank

  # Structure
  l$Structure <- coin$Meta$Lineage

  # Analysis
  l$Analysis <- coin$Analysis$Raw$FlaggedStats

  # Weights
  l$Weights <- f_get_last_weights(coin)

  # Data sets
  l <- c(l, coin$Data)

  # colours
  tab_colours <- list(
    Results = "green",
    Structure = "orange",
    Analysis = "blue",
    Weights = "yellow",
    Other = "grey"
  )

  # Write
  wb <- openxlsx::createWorkbook()

  options("openxlsx.borderStyle" = "thin")
  options("openxlsx.borderColour" = "white")

  lapply(names(l), function(s){

    if(s %in% c("Scores", "Ranks")){

      openxlsx::addWorksheet(wb, s, tabColour = tab_colours[["Results"]])
      openxlsx::writeData(wb, sheet = s, x = l[[s]])
      openxlsx::writeDataTable(wb, s, x = l[[s]],
                     tableStyle = "TableStyleMedium6",
                     bandedRows = FALSE)

      r_format <- 2: (nrow(l[[s]]) + 1)

      if(s == "Scores"){

        # index score
        openxlsx::conditionalFormatting(
          wb, s, cols = 4, rows = r_format,
          type = "databar")

        # Mov_Hum
        # cols = c(5, 16)
        openxlsx::conditionalFormatting(
          wb, s, cols = 5, rows = r_format,
          style = RColorBrewer::brewer.pal(n = 3, name = "YlOrRd"),
          type = "colourScale")

        # Amenazas
        # c(6, 9, 10)
        openxlsx::conditionalFormatting(
          wb, s, cols = 6, rows = r_format,
          style = RColorBrewer::brewer.pal(n = 3, name = "RdPu"),
          type = "colourScale")

        # Sit_SocEc
        # c(7, 17:20)
        openxlsx::conditionalFormatting(
          wb, s, cols = 7, rows = r_format,
          style = RColorBrewer::brewer.pal(n = 3, name = "PuBuGn"),
          type = "colourScale")

        # Sit_SocEc
        # cols = c(8, 11:15)
        openxlsx::conditionalFormatting(
          wb, s, cols = 8, rows = r_format,
          style = RColorBrewer::brewer.pal(n = 3, name = "YlGnBu"),
          type = "colourScale")

      }

    } else if (s %in% c("Structure", "Analysis", "Weights")) {

      openxlsx::addWorksheet(wb, s, tabColour = tab_colours[[s]])
      openxlsx::writeData(wb, sheet = s, x = l[[s]])

    } else {

      openxlsx::addWorksheet(wb, s, tabColour = tab_colours[["Other"]])
      openxlsx::writeData(wb, sheet = s, x = l[[s]])
    }

  })

  # write to excel
  openxlsx::saveWorkbook(wb, fname, overwrite = TRUE)
}
