# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Gather correlations
#' 
#' Helper function for indicator analysis
#' 
#' @param X a frame with the 2 indicators to check `"Ind1"`  Ind1 &  `"Ind1"`
#' 
#' @return  nothing a report is created...
#' 
#' @export
#' @examples
#' #f_gather_correlations()
f_gather_correlations <- function(X){

  Xpairs <- data.frame(v1 = c(X$Ind1, X$Ind2),
                       v2 = c(X$Ind2, X$Ind1))

  Xpairs <- Xpairs[order(Xpairs$v1, Xpairs$v2), ]

  tapply(Xpairs$v2, Xpairs$v1, paste0, collapse = ", ")
}
