# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Get equal weights
#' 
#' Returns a weight data frame of equal weights. Helper called by [f_change_weights()].
#' 
#' @param coin The coin
#' 
#' @return A data frame of weights. 
#' 
#' @export
#' @examples
#' #
f_get_equal_weights <- function(coin){

  w <- coin$Meta$Weights$Original
  stopifnot(!is.null(w))

  w$Weight <- 1

  return(w)
    
}
