# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Get last weights
#' 
#' Returns the data frame of weights last used to aggregate the coin. Helper
#' called by [f_change_weights()].
#' 
#' @param coin The coin
#' 
#' @return Data frame of weights.
#' 
#' @importFrom rlang abort
#' @export
#' @examples
#' #
f_get_last_weights <- function(coin){

  if(is.null(coin$Log$Aggregate)){
    return(NULL)
  }

  w_log <- coin$Log$Aggregate$w

  if(is.null(w_log)){

    w_new <- coin$Meta$Weights$Original

  } else if (is.character(w_log)){

    w_new <- coin$Meta$Weights[[w_log]]

  } else if (is.data.frame(w_log)){

    w_new <- w_log
  } else {
    rlang::abort("Weights not recognised at coin$Log$Aggregate$w")
  }

  stopifnot(is.data.frame(w_new))

  return(w_new)
    
}
