# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Get last weights
#' 
#' Description
#' 
#' @param coin COIN object, or list with first entry is the indicator metadata, 
#'              second entry is the aggregation metadata
#' @return w weight 
#' @importFrom rlang abort
#' @export
#' @examples
#' MVI <- f_data_input(file_path = system.file("data_input/data_module-input.xlsx",
#'                                             package = "BuildIndex") )
#' 
#' ## when using create a data-raw folder and put you data input xlsx file there
#' # MVI <- f_data_input(here::here("data-raw", "data_module-input.xlsx"))
#' MVI2 <- f_analyse_indicators(MVI)
#' MVI3 <- f_build_index(coin = MVI2)
#' weight <- f_get_last_weights(MVI3)
#' weight 
f_get_last_weights <- function(coin){

  if(is.null(coin$Log$Aggregate)){
    return(NULL)
  }

  w_log <- coin$Log$Aggregate$w

  if(is.null(w_log)){

    w_new <- coin$Meta$Weights$Original

  } else if (is.character(w_log)){

    w_new <- coin$Meta$Weights[[w_log]]

  } else if (is.data.frame(w_log)){

    w_new <- w_log
  } else {
    rlang::abort("Weights not recognised at coin$Log$Aggregate$w")
  }

  stopifnot(is.data.frame(w_new))

  return(w_new)
    
}
