# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Plot map
#' 
#' Plots an interactive choropleth map of the index or any indicator, using 
#' supplied shape files.
#' 
#' @param coin COIN object, or list with first entry is the indicator metadata, 
#'              second entry is the aggregation metadata
#' 
#' 
#' @param shp_path is currently at "shp/gtm_admbnda_adm2_ocha_conred_20190207.shp"
#' @importFrom COINr get_data
#' @importFrom sf read_sf
#' @importFrom leaflet leaflet labelOptions highlightOptions addTiles addLegend
#' @return
#' 
#' @export
#' @examples
#' MVI <- f_data_input(file_path = system.file("data_input/data_module-input.xlsx",
#'                                             package = "BuildIndex") )
#' 
#' ## when using create a data-raw folder and put you data input xlsx file there
#' # MVI <- f_data_input(here::here("data-raw", "data_module-input.xlsx"))
#' 
#' MVI2 <- f_build_index(coin = MVI)
#' 
#' f_plot_map(coin = MVI2, 
#'            dset = "Aggregated",
#'            iCode = "MVI", 
#'            shp_path = system.file("shp/gtm_admbnda_adm2_ocha_conred_20190207.shp",
#'                                             package = "BuildIndex")  )
#' ## when using ut your shape in the folder ---
#'          #  shp_path = here::here("inst/shp", "gtm_admbnda_adm2_ocha_conred_20190207.shp")           )
f_plot_map <- function(coin, 
                       dset = "Aggregated",
                       iCode = "MVI", 
                       shp_path){

 # shp <- read_sf("shp/gtm_admbnda_adm2_ocha_conred_20190207.shp")
  
  
  shp <- sf::read_sf(shp_path)
  

  # get data first
  df_plot <- COINr::get_data(coin, dset = dset, iCodes = iCode)

  # merge into shape df
  shp$Indicator <- df_plot[[iCode]][match(shp$ADM2_PCODE, df_plot$uCode)]

  # colorBin is a leaflet function
  pal <- leaflet::colorBin("YlOrRd", domain = shp$Indicator, bins = 7)

  # labels
  labels <- sprintf(
    "<strong>%s</strong><br/>%g",
    shp$ADM2_ES, round(shp$Indicator, 1)
  ) |>
    lapply(htmltools::HTML)


  # now we can make the map

  mp <- leaflet::leaflet(shp) |>
    leaflet::addTiles() |>
    leaflet::addPolygons(
      fillColor = ~pal(Indicator),
      weight = 2,
      opacity = 1,
      color = "white",
      dashArray = "3",
      fillOpacity = 0.7,
      highlightOptions = leaflet::highlightOptions(
        weight = 5,
        color = "#666",
        dashArray = "",
        fillOpacity = 0.7,
        bringToFront = TRUE),
      label = labels,
      labelOptions = leaflet::labelOptions(
        style = list("font-weight" = "normal", padding = "3px 8px"),
        textsize = "15px",
        direction = "auto")) |>
    leaflet::addLegend(pal = pal, values = ~Indicator, opacity = 0.7, title = NULL,
              position = "bottomright")

  mp
    
}
