# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Plot map with main index and sub index
#' 
#' @description Plots an interactive choropleth map using supplied shape files and powered by 
#' the leaflet package. This second version of the summary map display the main 
#' severity index together with all its sub-dimensions each them presented as 
#' selected layers. The infobox present the index (or subindex) value together 
#' with the rank. The shapefile is automatically simplified so that the resulting
#'  html viz remains light.
#' 
#' @param coin The coin
#' 
#' @param dset Name of data set in the coin from which to extract the 
#'             indicator/aggregate to plot
#'             
#' @param shp_path Assume a shapefile matching  with ucode  
#'           Guatemala example is currently at
#'            `"./inst/shp/gtm_admbnda_adm2_ocha_conred_20190207.shp"`
#'            
#' @param shp_name  name of corresponding admin unit in the shapefile "ADM2_ES"
#' 
#' @param shp_ucode name of corresponding admincode matching  with ucode 
#'    in the shapefile  for instance `"ADM2_PCODE"` being the main key to use
#'                                  
#' @param dTolerance  1000 per default - parameter to simplify the shapefile so that the report is not too heavy... 
#' 
#' @param palette color palette for the map - selected as "inferno" per default
#'        to be inclusive of color blind people                 
#' 
#' @importFrom COINr get_data
#' @importFrom sf read_sf st_simplify
#' @importFrom leaflet leaflet labelOptions 
#'                highlightOptions addTiles addLegend layersControlOptions
#' @importFrom dplyr rename select  left_join any_of
#' 
#' @return a leaflet object
#' 
#' @export

#' @examples
#' 
#' MVI <- f_data_input(file_path = system.file("data_input/data_module-input.xlsx",
#'                                             package = "BuildIndex") )
#' 
#' MVI <- f_build_index(MVI)
#' 
#' shp_path <-  system.file("data_input/gtm_admbnda_adm2_ocha_conred_20190207.shp",
#'                                             package = "BuildIndex")
#' 
#' shp_name <- "ADM2_ES"
#' shp_ucode <- "ADM2_PCODE"
#' 
#' f_plot_map2(coin = MVI, 
#'            dset = "Aggregated",
#'            shp_path = shp_path,
#'            shp_name = shp_name,
#'            shp_ucode = shp_ucode )      
f_plot_map2 <- function(coin, 
                       dset = "Aggregated",
                       shp_path,
                       shp_name,
                       shp_ucode ,
                       dTolerance = 1000,
                       palette= "inferno"){
  
  library(leaflet)
  requireNamespace("leaflet")
  requireNamespace("rgdal")
  # read shape file
  shp0 <-sf::read_sf(shp_path) |>
         dplyr::rename("shp_name"= any_of(shp_name) ,
                        "shp_ucode"= any_of(shp_ucode)  ) |>
         dplyr::select(geometry, shp_name, shp_ucode)


  shp <-  sf::st_simplify(shp0,
                          preserveTopology = TRUE,
                          dTolerance = 1000)

  # cat( paste0("shape size reduction through simplification is ",round( as.numeric( object.size(shp0)-object.size(shp))/as.numeric(object.size(shp0))*100),0), "%\n")

 ## extract the top 2 level
  agg <- coin$Log$new_coin$iMeta |>
         dplyr::filter(Level %in% c( max(Level), max(Level)-1))
  # get data first with to level dimension
  df_plot <-  COINr::get_data(coin, dset = dset) |>
             dplyr::select(uCode, agg$iCode)

  ## Subset the select indic - plus all the one on the level below -
  # merge into shape df
  shp <- shp |>
         dplyr::left_join( df_plot , by = c( "shp_ucode"= "uCode"))
  
  # Add multiple layers with a loop 
  indexLayer <- agg$iCode
  splist <- list()
  labellist <- list()
  pallist <- list()
  for (thislayern in 1:length(indexLayer)) {
    thislayer <- indexLayer[thislayern]
    #cat( paste0(thislayer, "\n"))
    splist[[thislayern]] <- shp |>
      dplyr::select(geometry, any_of(thislayer), shp_name)
    
    labellist[[thislayern]] <-  sprintf(
      "<strong>%s</strong><br/>Index %s: %g<br/>Rank: %g / %g",
      splist[[thislayern]]$shp_name,
      as.character(thislayer),
      round(as.numeric(splist[[thislayern]][[thislayer]]), 1),
      rank(-  splist[[thislayern]][[thislayer]]),
      as.integer(nrow(splist[[thislayern]]))     ) |>
      lapply(htmltools::HTML)
    
    pallist[[thislayern]] <- leaflet::colorBin(palette= "inferno",
                             domain =  splist[[thislayern]][[thislayer]],
                             pretty = TRUE,
                             na.color = "#dbdbdb",
                             bins = 7)
  
  }
    m <- leaflet::leaflet() |>
      leaflet::addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite")
    ## Add layers in a loop ----------------------------------
    for (thislayern in 1:length(indexLayer)) {
    # for (thislayern in 1:1) {
      thislayer <- indexLayer[thislayern]
       m <- m |>
          leaflet::addPolygons(
                          data = splist[[thislayern]],
                          group = thislayer,
                          fillColor = ~pallist[[thislayern]](splist[[thislayern]][[thislayer]]),
                          label = labellist[[thislayern]],
                          weight = 2,
                          opacity = 1,
                          color = "white",
                          dashArray = "2",
                          fillOpacity = 1,
                          highlightOptions = leaflet::highlightOptions(
                            weight = 5,
                            color = "#666",
                            dashArray = "",
                            fillOpacity = 0.7,
                            bringToFront = TRUE),
                          labelOptions = leaflet::labelOptions(
                            style = list("font-weight" = "normal", padding = "3px 8px"),
                            textsize = "15px",
                            direction = "auto"))   } # end of layers
    # Additional leaflet options ---------------------------------------------------
    m <- m |>
      # Add layers controls
      leaflet::addLayersControl(
        baseGroups = indexLayer,
        options = layersControlOptions(collapsed = FALSE)
      )
    # Add common legend
    # m <- m |>
    #   leaflet::addLegend(pal = pal,
    #                      values = ~ splist[[4]][[thislayer]],
    #                      opacity = 0.7,
    #                      title = NULL,
    #                      position = "bottomright")

  return(m)
    
}
