# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Plot map
#' 
#' Plots an interactive choropleth map of the index or any indicator, using 
#' supplied shape files. This is powered by the leaflet package.
#' 
#' Note we will need some checks here to make sure the shape file is compatible with the
#' data. This can be dealt with in the app phase.
#' 
#' @param coin The coin
#' @param dset Name of data set in the coin from which to extract the indicator/aggregate to plot
#' @param iCode Code of indicator within `dset` to plot
#' @param shp_path Guatemala example is currently at `"./inst/shp/gtm_admbnda_adm2_ocha_conred_20190207.shp"`
#' 
#' @importFrom COINr get_data
#' @importFrom sf read_sf
#' @importFrom leaflet leaflet labelOptions highlightOptions addTiles addLegend
#' 
#' @return a leaflet object
#' 
#' @export
#' @examples
#' MVI <- f_data_input(file_path = system.file("data_input/data_module-input.xlsx",
#'                                             package = "BuildIndex") )
#' 
#' MVI <- f_build_index(MVI)
#' 
#' f_plot_map(coin = MVI, 
#'            dset = "Aggregated",
#'            iCode = "MVI", 
#'            shp_path = system.file("shp/gtm_admbnda_adm2_ocha_conred_20190207.shp",
#'                                             package = "BuildIndex")  )
#' ## when using ut your shape in the folder ---
#'          #  shp_path = here::here("inst/shp", "gtm_admbnda_adm2_ocha_conred_20190207.shp")           )
f_plot_map <- function(coin, 
                       dset = "Aggregated",
                       iCode = "MVI", 
                       shp_path){
  
  # read shape file
  shp <- sf::read_sf(shp_path)

  # get data first
  df_plot <- COINr::get_data(coin, dset = dset, iCodes = iCode)

  # merge into shape df
  shp$Indicator <- df_plot[[iCode]][match(shp$ADM2_PCODE, df_plot$uCode)]

  # colorBin is a leaflet function
  pal <- leaflet::colorBin("YlOrRd", domain = shp$Indicator, bins = 7)

  # labels
  labels <- sprintf(
    "<strong>%s</strong><br/>%g",
    shp$ADM2_ES, round(shp$Indicator, 1)
  ) |>
    lapply(htmltools::HTML)


  # now we can make the map

  mp <- leaflet::leaflet(shp) |>
    leaflet::addTiles() |>
    leaflet::addPolygons(
      fillColor = ~pal(Indicator),
      weight = 2,
      opacity = 1,
      color = "white",
      dashArray = "3",
      fillOpacity = 0.7,
      highlightOptions = leaflet::highlightOptions(
        weight = 5,
        color = "#666",
        dashArray = "",
        fillOpacity = 0.7,
        bringToFront = TRUE),
      label = labels,
      labelOptions = leaflet::labelOptions(
        style = list("font-weight" = "normal", padding = "3px 8px"),
        textsize = "15px",
        direction = "auto")) |>
    leaflet::addLegend(pal = pal, values = ~Indicator, opacity = 0.7, title = NULL,
              position = "bottomright")

  mp
    
}
