# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Remove indicators
#' 
#' Removes indicators as specified by a character vector of indicator
#' codes in `remove_indicators`. After removal, any results are regenerated
#' (updated).
#' 
#' The original data is always preserved so indicators can be restored.
#' Analysis tables are not currently re-run so this would have to be done separately.
#' However, there is actually no need to re-run.
#' 
#' @param coin A coin.
#' @param remove_indicators  Character vector of indicator codes to remove.
#' 
#' @importFrom COINr change_ind              
#' 
#' @return coin COIN object
#' 
#' @export
#' @examples
#' MVI <- f_data_input(file_path = system.file("data_input/data_module-input.xlsx",
#'                                             package = "BuildIndex") )
#' 
#' # call print method
#' MVI
#' 
#' MVI <- f_remove_indicators(MVI, c("S.G.3", "A.M.1"))
#' # compare with previous
#' MVI
f_remove_indicators <- function(coin, 
                                remove_indicators = NULL){

  # extract analysis
  ind_analysis <- coin$Analysis$Raw
  analysis_exists <- !is.null(ind_analysis)

  coin <- COINr::change_ind(coin, drop = remove_indicators, regen = TRUE)

  if(analysis_exists){
    # edit and replace analysis
    ind_analysis$FlaggedStats$Status[
      ind_analysis$FlaggedStats$iCode %in% remove_indicators] <- "OUT"
    ind_analysis$Flags$Status[
      ind_analysis$Flags$iCode %in% remove_indicators] <- TRUE

    coin$Analysis$Raw <- ind_analysis
  }

  if(!is.null(coin$Data$Aggregated)){
    coin <- f_generate_results(coin)
  }

  return(coin)
    
}
