# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Remove indicators
#' 
#' Removes indicators as specified by a character vector of indicator
#' codes in `remove_indicators`. After removal, any results are regenerated
#' (updated).
#' 
#' The original data is always preserved so indicators can be restored.
#' Analysis tables are not currently re-run so this has to be done separately.
#' 
#' @param coin COIN object, or list with first entry is the indicator metadata, 
#'              second entry is the aggregation metadata
#' @param remove_indicators  
#' @importFrom COINr change_ind              
#' 
#' @return coin COIN object
#' 
#' @export
#' @examples
#' MVI <- f_data_input(file_path = system.file("data_input/data_module-input.xlsx",
#'                                             package = "BuildIndex") )
#' 
#' ## when using create a data-raw folder and put you data input xlsx file there
#' # MVI <- f_data_input(here::here("data-raw", "data_module-input.xlsx"))
#' MVI2 <- f_analyse_indicators(MVI)
#' MVI3 <- f_remove_indicators(MVI2, c("S.G.3", "A.M.1"))
#' MVI3
f_remove_indicators <- function(coin, 
                                remove_indicators = NULL){

  # extract analysis
  ind_analysis <- coin$Analysis$Raw
  analysis_exists <- !is.null(ind_analysis)

  coin <- COINr::change_ind(coin, drop = remove_indicators, regen = TRUE)

  if(analysis_exists){
    # edit and replace analysis
    ind_analysis$FlaggedStats$Status[
      ind_analysis$FlaggedStats$iCode %in% remove_indicators] <- "OUT"
    ind_analysis$Flags$Status[
      ind_analysis$Flags$iCode %in% remove_indicators] <- TRUE

    coin$Analysis$Raw <- ind_analysis
  }

  if(!is.null(coin$Data$Aggregated)){
    coin <- f_generate_results(coin)
  }

  return(coin)
    
}
