# WARNING - Generated by {fusen} from /dev/severity_index.Rmd: do not edit by hand

#' Codes of any groups with only one child
#' 
#' To avoid errors in Compind functions
#' 
#' @param coin The coin
#' 
#' @noRd
#' @examples
#' #
get_solo_groups <- function(coin){
  imeta <- coin$Meta$Ind
  parents <- imeta$Parent[!is.na(imeta$Parent)]
  x[which(!(duplicated(x) | duplicated(x, fromLast = TRUE)))]
}
